/**
 * Embedded subset of the names dataset (from Karpathy's makemore).
 * ~200 names for fast in-browser training.
 */
export const NAMES: string[] = [
  "emma", "olivia", "ava", "sophia", "isabella",
  "mia", "charlotte", "amelia", "harper", "evelyn",
  "abigail", "emily", "ella", "elizabeth", "camila",
  "luna", "sofia", "avery", "mila", "aria",
  "scarlett", "penelope", "layla", "chloe", "victoria",
  "madison", "eleanor", "grace", "nora", "riley",
  "zoey", "hannah", "hazel", "lily", "ellie",
  "violet", "lillian", "zoe", "stella", "aurora",
  "natalie", "emilia", "everly", "leah", "aubrey",
  "willow", "addison", "lucy", "audrey", "bella",
  "nova", "brooklyn", "paisley", "savannah", "claire",
  "skylar", "isla", "genesis", "naomi", "elena",
  "caroline", "eliana", "anna", "maya", "valentina",
  "ruby", "kennedy", "ivy", "ariana", "aaliyah",
  "cora", "madelyn", "alice", "kinsley", "hailey",
  "liam", "noah", "oliver", "james", "elijah",
  "william", "henry", "lucas", "benjamin", "theodore",
  "jack", "levi", "alexander", "mason", "ethan",
  "daniel", "jacob", "michael", "logan", "jackson",
  "sebastian", "aiden", "mateo", "samuel", "owen",
  "ryan", "david", "leo", "john", "luke",
  "julian", "hudson", "grayson", "wyatt", "carter",
  "gabriel", "jayden", "luca", "maverick", "ezra",
  "lincoln", "asher", "kai", "thomas", "charles",
  "caleb", "christopher", "josiah", "ezekiel", "miles",
  "nathan", "adam", "eli", "nolan", "connor",
  "aaron", "adrian", "cameron", "roman", "colton",
  "ian", "jordan", "axel", "max", "brooks",
  "dominic", "austin", "robert", "chase", "zander",
  "declan", "angel", "ivan", "jose", "ayden",
  "carson", "jaxon", "easton", "maverick", "bryson",
  "xavier", "damian", "rowan", "braxton", "sawyer",
  "archer", "atlas", "kingston", "phoenix", "silas",
  "blake", "quinn", "finn", "hayden", "jasper",
  "cole", "theo", "felix", "riley", "beau",
  "dante", "tucker", "sean", "emmet", "cruz",
  "beckett", "paxton", "jude", "knox", "grant",
  "river", "arlo", "rhett", "otto", "reed",
  "leon", "milo", "ace", "axel", "wells",
  "hugo", "alan", "dean", "dawson", "zion",
];
